### ISSUE TITLE
Add support for Zapstore

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#74]
[Zapstore](https://zapstore.dev) - a Nostr-based app store where we can sign releases with our BTC Map nsec.

Here is the [CLI Tool](https://github.com/zapstore/zapstore-cli?tab=readme-ov-file). Here are the [Publishing Instructions](https://zapstore.dev/docs/cli/publish/).

The following command works `zapstore publish btcmap --overwrite-release --overwrite-app --icon icon.png`.

The following zapstore.yaml works:

```
btcmap:
  android:
    repository: https://github.com/teambtcmap/btcmap-android
    license: AGPL v3
    name: BTC Map
    description: Easily find places to spend sats anywhere on the planet.
    artifacts:
      -  btcmap-%v.apk
```
